version: '3.4'

services:
  kramerbotui:
    image: kramerbotui
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173
